# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n-1)/2   1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n-1)   1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

require 'set'

ti = 286
pi = 166
hi = 144
tl = pl = hl = 40755

while true do
  tl = tl + ti
  ti += 1
  while tl > pl do
    pl = pl + 3 * pi - 2
    pi += 1
  end
  while tl > hl do
    hl = hl + 4 * hi - 3
    hi += 1
  end
  puts "#{ti}, #{pi}, #{hi}"
  if tl == pl and tl == hl then
    abort tl.to_s
  end
end