
#define CONTENT_FONT_SIZE 16.0
#define SUBTASK_FONT_SIZE 14.0
#define CHECK_BUTTON_SIZE 40.0
#define DATE_FONT_SIZE 11.0
#define SECTION_HEIGHT 30.0
#define SCREEN_WIDTH 320
#define SINGLE_LINE_CELL_HEIGHT 40.0
#define DOUBLE_LINE_CELL_HEIGHT 60.0
#define TOOLBAR_HEIGHT 43.0

#define DB_NAME @"todo.db"