#!/usr/bin/expect -f

set timeout -1
spawn killall ssh
spawn ssh -D 7777 -N router@ssh.uapp.info
set spawnid $spawn_id
expect "*?assword:*"
send -- "eZC!-Bcm1)mV"
send -- "\r"
spawn say connected
expect -i $spawnid eof
spawn say connection broken
