#!/usr/bin/expect -f

set timeout -1
spawn killall ssh
spawn ssh -D 7777 -p 80 -N hhhtj@ssh.csball.com
set spawnid $spawn_id
expect "*?assword:*"
send -- "deqrpl"
send -- "\r"
spawn say connected
expect -i $spawnid eof
spawn say connection broken
